In [5]:
import numpy as np
import pandas as pd
import random
from datetime import datetime, timedelta

np.random.seed(42)
random.seed(42)

print("Libraries imported successfully!")

Libraries imported successfully!

In [6]:
NUM_USERS = 10000
NUM_TRANSACTIONS = 200000
NUM_MERCHANTS = 500
NUM_DEVICES = 15000

In [7]:
START_DATE = pd.Timestamp("2026-01-01")
END_DATE = pd.Timestamp("2026-06-30")

In [9]:
user_ids = [
    f"U{str(i).zfill(5)}"
    for i in range(1, NUM_USERS + 1)
]

In [10]:
customer_segments = [
    "Regular",
    "Premium",
    "Business"
]

In [11]:
users_df = pd.DataFrame({
    "user_id": user_ids,
    "account_age_days": np.random.randint(
        30, 2500, NUM_USERS
    ),
    "customer_segment": np.random.choice(
        customer_segments,
        NUM_USERS,
        p=[0.75, 0.20, 0.05]
    )
})
print(users_df)

     user_id  account_age_days customer_segment
0     U00001               890          Regular
1     U00002              1324          Regular
2     U00003              1160          Regular
3     U00004              1125          Regular
4     U00005              1668          Regular
...      ...               ...              ...
9995  U09996              1305          Regular
9996  U09997              1908          Regular
9997  U09998              2388          Premium
9998  U09999               630          Regular
9999  U10000               504          Regular

[10000 rows x 3 columns]

In [13]:
locations = {
    "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad"],
    "Bihar": ["Patna", "Gaya", "Muzaffarpur"],
    "Delhi": ["New Delhi"],
    "Maharashtra": ["Mumbai", "Pune", "Nagpur"],
    "Karnataka": ["Bengaluru", "Mysuru"],
    "West Bengal": ["Kolkata", "Durgapur"],
    "Uttar Pradesh": ["Lucknow", "Noida", "Varanasi"],
    "Telangana": ["Hyderabad"],
    "Tamil Nadu": ["Chennai", "Coimbatore"],
    "Rajasthan": ["Jaipur", "Jodhpur"]
}
# print(locations)

In [14]:
state_list = list(locations.keys())

In [15]:
user_states = np.random.choice(
    state_list,
    NUM_USERS
)
user_states

array(['Karnataka', 'Rajasthan', 'West Bengal', ..., 'Maharashtra',
       'Telangana', 'Karnataka'], shape=(10000,), dtype='<U13')

In [16]:
def choose_city(state):
    return random.choice(locations[state])

In [17]:
user_cities = [
    choose_city(state)
    for state in user_states
]

In [18]:
users_df = pd.DataFrame({
    "user_id": user_ids,
    "account_age_days": np.random.randint(
        30, 2500, NUM_USERS
    ),
    "customer_segment": np.random.choice(
        ["Regular", "Premium", "Business"],
        NUM_USERS,
        p=[0.75, 0.20, 0.05]
    ),
    "state": user_states,
    "city": user_cities
})
# print(users_df)

In [19]:
users_df.head()

  user_id  account_age_days customer_segment        state       city
0  U00001                63          Regular    Karnataka  Bengaluru
1  U00002               325          Premium    Rajasthan     Jaipur
2  U00003              1459          Regular  West Bengal   Durgapur
3  U00004              1180          Regular        Delhi  New Delhi
4  U00005              2219          Regular    Karnataka  Bengaluru

In [20]:
users_df.shape

(10000, 5)

In [21]:
users_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10000 non-null  str
 1   account_age_days  10000 non-null  int32
 2   customer_segment  10000 non-null  str
 3   state             10000 non-null  str
 4   city              10000 non-null  str
dtypes: int32(1), str(4)
memory usage: 351.7 KB

In [22]:
users_df.isnull().sum()

user_id             0
account_age_days    0
customer_segment    0
state               0
city                0
dtype: int64

In [23]:
users_df["customer_segment"].value_counts()

customer_segment
Regular     7486
Premium     1983
Business     531
Name: count, dtype: int64

In [24]:
users_df["state"].value_counts()

state
Karnataka        1085
Uttar Pradesh    1030
Delhi            1027
Maharashtra      1006
Rajasthan         997
Tamil Nadu        995
West Bengal       985
Telangana         985
Jharkhand         951
Bihar             939
Name: count, dtype: int64

In [25]:
merchant_ids = [
    f"M{str(i).zfill(4)}"
    for i in range(1, NUM_MERCHANTS + 1)
]

In [26]:
merchant_categories = [
    "E-Commerce",
    "Grocery",
    "Food",
    "Travel",
    "Utilities",
    "Healthcare",
    "Education",
    "Entertainment",
    "Fuel",
    "Other"
]

In [27]:
device_ids = [
    f"DEV{str(i).zfill(5)}"
    for i in range(1, NUM_DEVICES + 1)
]

In [28]:
users_df.to_csv(
    "../DATA/RAW/users_raw.csv",
    index=False
)

In [29]:
import os 
os.path.exists("../DATA/RAW/users_raw.csv")

True

In [30]:
pd.read_csv("../DATA/RAW/users_raw.csv")

     user_id  account_age_days customer_segment        state       city
0     U00001                63          Regular    Karnataka  Bengaluru
1     U00002               325          Premium    Rajasthan     Jaipur
2     U00003              1459          Regular  West Bengal   Durgapur
3     U00004              1180          Regular        Delhi  New Delhi
4     U00005              2219          Regular    Karnataka  Bengaluru
...      ...               ...              ...          ...        ...
9995  U09996              1650          Regular    Jharkhand    Dhanbad
9996  U09997               371         Business        Bihar      Patna
9997  U09998               964          Premium  Maharashtra     Nagpur
9998  U09999               617          Regular    Telangana  Hyderabad
9999  U10000              2409          Premium    Karnataka     Mysuru

[10000 rows x 5 columns]

In [31]:
merchant_ids = [
    f"M{str(i).zfill(4)}"
    for i in range(1, NUM_MERCHANTS + 1)
]

In [76]:
merchant_categories = [
    "E-Commerce",
    "Grocery",
    "Food",
    "Travel",
    "Utilities",
    "Healthcare",
    "Education",
    "Entertainment",
    "Fuel",
    "Other"
]

In [77]:
category_probabilities = [
    0.18,  # E-Commerce
    0.15,  # Grocery
    0.15,  # Food
    0.08,  # Travel
    0.10,  # Utilities
    0.07,  # Healthcare
    0.05,  # Education
    0.08,  # Entertainment
    0.09,  # Fuel
    0.05   # Other
]

In [78]:
merchant_category_values = np.random.choice(
    merchant_categories,
    NUM_MERCHANTS,
    p=category_probabilities
)

In [79]:
merchant_states = np.random.choice(
    state_list,
    NUM_MERCHANTS
)

In [80]:
merchant_cities = [
    choose_city(state)
    for state in merchant_states
]

In [81]:
merchant_risk_categories = [
    "Normal",
    "Elevated",
    "High"
]

In [82]:
merchant_risk_values = np.random.choice(
    merchant_risk_categories,
    NUM_MERCHANTS,
    p=[0.75, 0.20, 0.05]
)

In [83]:
merchant_names = [
    f"MERCHANT_{str(i).zfill(4)}"
    for i in range(1, NUM_MERCHANTS + 1)
]

In [84]:
merchants_df = pd.DataFrame({
    "merchant_id": merchant_ids,
    "merchant_name": merchant_names,
    "merchant_category": merchant_category_values,
    "state": merchant_states,
    "city": merchant_cities,
    "merchant_risk_category": merchant_risk_values
})

In [85]:
# merchants_df.head()

In [86]:
merchants_df.shape

(500, 6)

In [87]:
# merchants_df.info()

In [88]:
# merchants_df.isnull().sum()

In [89]:
# merchants_df["merchant_category"].value_counts()

In [90]:
# merchants_df["merchant_risk_category"].value_counts()

In [91]:
merchants_df.to_csv(
    "../DATA/RAW/merchants_raw.csv",
    index=False
)

In [92]:
os.path.exists("../DATA/RAW/merchants_raw.csv")

True

In [93]:
len(device_ids)

15000

In [94]:
device_types = [
    "Mobile",
    "Tablet",
    "Web"
]

In [95]:
device_type_probabilities = [
    0.82,   # Mobile
    0.08,   # Tablet
    0.10    # Web
]

In [96]:
operating_systems = [
    "Android",
    "iOS",
    "Windows",
    "macOS"
]

In [97]:
device_os_mapping = {
    "Mobile": ["Android", "iOS"],
    "Tablet": ["Android", "iOS"],
    "Web": ["Windows", "macOS"]
}

In [98]:
def choose_os(device_type):
    return random.choice(device_os_mapping[device_type])

In [99]:
# choose_os("Tablet")

In [100]:
# choose_os("Web")

In [101]:
device_type_values = np.random.choice(
    device_types,
    NUM_DEVICES,
    p=device_type_probabilities
)

In [102]:
# len(device_type_values)

In [103]:
device_os_values = [
    choose_os(device_type)
    for device_type in device_type_values
]

In [104]:
DEVICE_START_DATE = pd.Timestamp("2025-01-01")
DEVICE_END_DATE = pd.Timestamp("2026-06-30")

In [105]:
device_registration_dates = pd.to_datetime(
    np.random.randint(
        DEVICE_START_DATE.value // 10**9,
        DEVICE_END_DATE.value // 10**9,
        NUM_DEVICES
    ),
    unit="s"
)

In [106]:
devices_df = pd.DataFrame({
    "device_id": device_ids,
    "device_type": device_type_values,
    "os": device_os_values,
    "registration_date": device_registration_dates
})

In [107]:
# devices_df.head()

In [108]:
# devices_df.shape

In [109]:
# devices_df.info()

In [110]:
# devices_df.isnull().sum()

In [111]:
# devices_df["device_type"].value_counts()

In [112]:
# devices_df["os"].value_counts()

In [113]:
# pd.crosstab(
#     devices_df["device_type"],
#     devices_df["os"]
# )

In [114]:
devices_df.to_csv(
    "../DATA/RAW/devices_raw.csv",
    index=False
)

In [115]:
# os.path.exists("../DATA/RAW/devices_raw.csv")

In [116]:
primary_device = np.random.choice(device_ids,NUM_USERS,replace=False)

In [117]:
user_device_mapping = pd.DataFrame(
     {
         "user_id":user_ids,
         "device_id":np.random.choice(device_ids,NUM_USERS,replace=False),
     })

In [118]:
# user_device_mapping.info()

In [119]:
# user_device_mapping.nunique()
# user_device_mapping["user_id"].nunique()
# user_device_mapping["device_id"].nunique()
# user_device_mapping.shape
# user_device_mapping.nunique()
# user_device_mapping.duplicated()

In [120]:
user_device_mapping["user_id"].value_counts().value_counts()

count
1    10000
Name: count, dtype: int64

In [121]:
user_device_mapping["is_primary_device"]=True
user_device_mapping.head()

  user_id device_id  is_primary_device
0  U00001  DEV07733               True
1  U00002  DEV05392               True
2  U00003  DEV14090               True
3  U00004  DEV13684               True
4  U00005  DEV02819               True

In [122]:
first_seen_dates=pd.to_datetime(np.random.randint(
        START_DATE.value // 10**9,
        END_DATE.value // 10**9,
        NUM_USERS
    ),
    unit="s"
)

In [123]:
user_device_mapping["first_seen_date"]=first_seen_dates

In [124]:
# user_device_mapping.head()
# user_device_mapping.info()
# user_device_mapping["first_seen_date"].describe()
# user_device_mapping.isnull().sum()

In [125]:
SECONDARY_USER_COUNT = int(NUM_USERS * 0.18)

secondary_users = np.random.choice(
    user_ids,
    SECONDARY_USER_COUNT,
    replace=False
)
len(secondary_users)

1800

In [126]:
pd.Series(secondary_users).duplicated().sum()

np.int64(0)

In [127]:
used_devices = set(user_device_mapping["device_id"])

In [128]:
available_devices = list(
    set(device_ids) - used_devices
)

In [129]:
secondary_devices = np.random.choice(
    available_devices,
    SECONDARY_USER_COUNT,
    replace=False
)

In [130]:
pd.Series(secondary_devices).duplicated().sum()

np.int64(0)

In [131]:
secondary_first_seen = pd.to_datetime(
    np.random.randint(
        START_DATE.value // 10**9,
        END_DATE.value // 10**9,
        SECONDARY_USER_COUNT
    ),
    unit="s"
)

In [132]:
secondary_mapping = pd.DataFrame({
     "user_id":secondary_users,
     "device_id":secondary_devices,
     "is_primary_device": False,
     "first_seen_date": secondary_first_seen
})

In [133]:
user_device_mapping = pd.concat(
    [user_device_mapping, secondary_mapping],
    ignore_index=True
)

In [134]:
user_device_mapping.shape

(11800, 4)

In [135]:
# user_device_mapping["is_primary_device"].value_counts()

In [136]:
# user_device_mapping["user_id"].value_counts().value_counts()

In [137]:
# secondary_mapping.shape

In [138]:
# secondary_mapping["user_id"].value_counts().head(10)

In [139]:
# SECONDARY_USER_COUNT

In [140]:
# len(secondary_users)

In [141]:
# len(secondary_devices)

In [142]:
secondary_mapping = pd.DataFrame({
    "user_id": secondary_users,
    "device_id": secondary_devices,
    "is_primary_device": False,
    "first_seen_date": secondary_first_seen
})

In [143]:
secondary_mapping.shape

(1800, 4)

In [144]:
len(primary_device)

10000

In [145]:
len(user_device_mapping)

11800

In [146]:
user_device_mapping.shape

(11800, 4)

In [147]:
primary_devices = np.random.choice(
    device_ids,
    NUM_USERS,
    replace=False
)

user_device_mapping = pd.DataFrame({
    "user_id": user_ids,
    "device_id": primary_devices
})

user_device_mapping["is_primary_device"] = True
user_device_mapping["first_seen_date"] = first_seen_dates

In [148]:
user_device_mapping = pd.concat(
    [user_device_mapping, secondary_mapping],
    ignore_index=True
)

In [149]:
user_device_mapping.shape

(11800, 4)

In [150]:
user_device_mapping["is_primary_device"].value_counts()

is_primary_device
True     10000
False     1800
Name: count, dtype: int64

In [151]:
user_device_mapping["user_id"].value_counts().value_counts()

count
1    8200
2    1800
Name: count, dtype: int64

In [152]:
# secondary_mapping.shape
# user_device_mapping.shape

user_device_mapping["user_id"].value_counts().value_counts()

count
1    8200
2    1800
Name: count, dtype: int64

In [153]:
SHARED_DEVICE_COUNT = 100

shared_devices = np.random.choice(
    available_devices,
    SHARED_DEVICE_COUNT,
    replace=False
)

In [154]:
shared_rows = []

In [155]:
for device in shared_devices:

    selected_users = np.random.choice(
        user_ids,
        3,
        replace=False
    )

    random_dates = pd.to_datetime(
        np.random.randint(
            START_DATE.value // 10**9,
            END_DATE.value // 10**9,
            3
        ),
        unit="s"
    )

    for user, date in zip(selected_users, random_dates):

        shared_rows.append({
            "user_id": user,
            "device_id": device,
            "is_primary_device": False,
            "first_seen_date": date
        })

In [156]:
shared_mapping = pd.DataFrame(shared_rows)

In [157]:
shared_mapping.shape

(300, 4)

In [158]:
user_device_mapping = pd.concat(
    [user_device_mapping, shared_mapping],
    ignore_index=True
)

In [159]:
user_device_mapping.shape

(12100, 4)

In [160]:
user_device_mapping["device_id"].value_counts().head(10)

device_id
DEV08795    5
DEV11117    5
DEV07842    5
DEV07640    5
DEV07290    5
DEV13387    5
DEV00377    5
DEV13438    5
DEV04198    5
DEV05838    5
Name: count, dtype: int64

In [161]:
user_device_mapping.to_csv(
    "../DATA/RAW/user_device_mapping_raw.csv",
    index=False
)

In [162]:
import os
os.path.exists("../DATA/RAW/user_device_mapping_raw.csv")

True

In [163]:
pd.read_csv("../DATA/RAW/user_device_mapping_raw.csv").head()

  user_id device_id  is_primary_device      first_seen_date
0  U00001  DEV11582               True  2026-04-29 00:38:44
1  U00002  DEV03815               True  2026-06-09 16:43:26
2  U00003  DEV13751               True  2026-05-08 09:28:35
3  U00004  DEV07368               True  2026-02-03 01:32:41
4  U00005  DEV12087               True  2026-05-20 05:21:50

In [164]:
pd.read_csv("../DATA/RAW/user_device_mapping_raw.csv").shape

(12100, 4)

In [165]:
user_device_mapping

      user_id device_id  is_primary_device     first_seen_date
0      U00001  DEV11582               True 2026-04-29 00:38:44
1      U00002  DEV03815               True 2026-06-09 16:43:26
2      U00003  DEV13751               True 2026-05-08 09:28:35
3      U00004  DEV07368               True 2026-02-03 01:32:41
4      U00005  DEV12087               True 2026-05-20 05:21:50
...       ...       ...                ...                 ...
12095  U04298  DEV08345              False 2026-05-14 08:04:56
12096  U00992  DEV08345              False 2026-01-23 21:23:32
12097  U00140  DEV01868              False 2026-03-08 07:23:57
12098  U00780  DEV01868              False 2026-05-12 13:12:38
12099  U03813  DEV01868              False 2026-02-11 07:04:48

[12100 rows x 4 columns]

In [166]:
transaction_ids = [
    f"TXN{str(i).zfill(7)}"
    for i in range(1, NUM_TRANSACTIONS + 1)
]

In [167]:
len(transaction_ids)

200000

In [168]:
transaction_ids[:5]

['TXN0000001', 'TXN0000002', 'TXN0000003', 'TXN0000004', 'TXN0000005']

In [169]:
transaction_ids[-5:]

['TXN0199996', 'TXN0199997', 'TXN0199998', 'TXN0199999', 'TXN0200000']

In [170]:
transactions_df = pd.DataFrame({
    "transaction_id": transaction_ids
})

In [171]:
transactions_df.shape

(200000, 1)

In [172]:
# transactions_df.info()

In [173]:
date_range = pd.date_range(
    START_DATE,
    END_DATE,
    freq="D"
)

transaction_dates = np.random.choice(
    date_range,
    NUM_TRANSACTIONS
)

In [174]:
hour_probabilities = [ 
    0.0097, # 00
    0.0048, # 01
    0.0029, # 02
    0.0019, # 03
    0.0019, # 04
    0.0029, # 05
    0.0194, # 06
    0.0388, # 07
    0.0485, # 08
    0.0679, # 09
    0.0776, # 10
    0.0582, # 11
    0.0485, # 12
    0.0582, # 13
    0.0485, # 14
    0.0388, # 15
    0.0388, # 16
    0.0485, # 17
    0.0679, # 18
    0.0873, # 19
    0.0971, # 20
    0.0776, # 21
    0.0388, # 22
    0.0155  # 23
]

In [175]:
sum(hour_probabilities)

1.0

In [176]:
transaction_hours = np.random.choice(
         range(24),
         NUM_TRANSACTIONS,
         p=hour_probabilities
)

In [177]:
transaction_minutes = np.random.randint(
    0,
    60,
    NUM_TRANSACTIONS
)

transaction_seconds = np.random.randint(
    0,
    60,
    NUM_TRANSACTIONS
)

In [178]:
transactions_df["timestamp"] = (
    pd.to_datetime(transaction_dates)
    + pd.to_timedelta(transaction_hours, unit="h")
    + pd.to_timedelta(transaction_minutes, unit="m")
    + pd.to_timedelta(transaction_seconds, unit="s")
)

In [179]:
transactions_df

       transaction_id           timestamp
0          TXN0000001 2026-01-22 10:12:58
1          TXN0000002 2026-04-02 11:13:32
2          TXN0000003 2026-03-18 20:41:24
3          TXN0000004 2026-03-18 20:20:34
4          TXN0000005 2026-02-09 21:34:04
...               ...                 ...
199995     TXN0199996 2026-03-11 13:10:57
199996     TXN0199997 2026-06-27 14:20:58
199997     TXN0199998 2026-04-04 17:08:44
199998     TXN0199999 2026-05-28 14:43:46
199999     TXN0200000 2026-04-06 16:39:19

[200000 rows x 2 columns]

In [180]:
transactions_df["timestamp"].min()
# transactions_df["timestamp"].max()

Timestamp('2026-01-01 00:06:03')

In [181]:
transactions_df["timestamp"].dt.hour.value_counts().sort_index()

timestamp
0      1979
1       981
2       560
3       393
4       413
5       575
6      4009
7      7698
8      9629
9     13711
10    15484
11    11809
12     9634
13    11543
14     9630
15     7954
16     7729
17     9679
18    13545
19    17472
20    19554
21    15050
22     7988
23     2981
Name: count, dtype: int64

In [182]:
segment_weights = {
    "Regular": 1,
    "Premium": 2,
    "Business": 4
}

In [183]:
user_weights = (
    users_df["customer_segment"]
    .map(segment_weights)
)

In [184]:
user_weights

0       1
1       2
2       1
3       1
4       1
       ..
9995    1
9996    4
9997    2
9998    1
9999    2
Name: customer_segment, Length: 10000, dtype: int64

In [185]:
user_probabilities = (
    user_weights
    / user_weights.sum()
)

In [186]:
user_probabilities.sum()

np.float64(1.0)

In [187]:
transactions_df["user_id"] = np.random.choice(
    users_df["user_id"],
    NUM_TRANSACTIONS,
    p=user_probabilities
)

In [188]:
transactions_df["user_id"].value_counts().head(10)

user_id
U01160    87
U08642    82
U07519    78
U07057    78
U03519    78
U09162    76
U03844    76
U01409    75
U05757    75
U03327    75
Name: count, dtype: int64

In [189]:
user_device_dict = (
    user_device_mapping
    .groupby("user_id")["device_id"]
    .apply(list)
    .to_dict()
)

In [190]:
# user_device_dict

In [191]:
transactions_df["device_id"] = (
    transactions_df["user_id"]
    .apply(lambda x: random.choice(user_device_dict[x]))
)

In [192]:
transactions_df[
    ["user_id","device_id"]
].head()

  user_id device_id
0  U03855  DEV06706
1  U03984  DEV08663
2  U03867  DEV11055
3  U04995  DEV03254
4  U08774  DEV10449

In [193]:
merchant_weight_map = {
    "Grocery": 5,
    "Food": 5,
    "Utilities": 4,
    "Fuel": 3,
    "E-Commerce": 3,
    "Healthcare": 2,
    "Entertainment": 2,
    "Travel": 1,
    "Education": 1,
    "Other": 1
}

In [194]:
merchant_weights = (
    merchants_df["merchant_category"]
    .map(merchant_weight_map)
)

In [195]:
merchant_probabilities = (
    merchant_weights
    / merchant_weights.sum()
)

In [196]:
merchant_probabilities.sum()

np.float64(1.0)

In [197]:
transactions_df["merchant_id"] = np.random.choice(
    merchants_df["merchant_id"],
    NUM_TRANSACTIONS,
    p=merchant_probabilities
)

In [198]:
transactions_df.shape

(200000, 5)

In [199]:
transactions_df.isnull().sum()

transaction_id    0
timestamp         0
user_id           0
device_id         0
merchant_id       0
dtype: int64

In [200]:
transactions_df["merchant_id"].value_counts().head()

merchant_id
M0004    683
M0361    681
M0227    679
M0024    674
M0216    671
Name: count, dtype: int64

In [201]:
transactions_df["timestamp"].dt.hour.value_counts().sort_index()

timestamp
0      1979
1       981
2       560
3       393
4       413
5       575
6      4009
7      7698
8      9629
9     13711
10    15484
11    11809
12     9634
13    11543
14     9630
15     7954
16     7729
17     9679
18    13545
19    17472
20    19554
21    15050
22     7988
23     2981
Name: count, dtype: int64

In [202]:
# transactions_df.shape

# sum(hour_probabilities)

# transactions_df["timestamp"].min()

# transactions_df["timestamp"].max()

# transactions_df["timestamp"].dt.hour.value_counts().sort_index().head(10)

# transactions_df["user_id"].value_counts().head(5)

# transactions_df["merchant_id"].value_counts().head(5)

transactions_df.isnull().sum()

transaction_id    0
timestamp         0
user_id           0
device_id         0
merchant_id       0
dtype: int64

In [203]:
transaction_types = np.random.choice(
    ["P2M","P2P","Bill"],
    NUM_TRANSACTIONS,
    p=[0.75,0.20,0.05]
)

transactions_df["transaction_type"] = transaction_types

In [204]:
transactions_df["transaction_type"].value_counts()

transaction_type
P2M     149795
P2P      40273
Bill      9932
Name: count, dtype: int64

In [205]:
merchant_category_map = (
    merchants_df
    .set_index("merchant_id")["merchant_category"]
    .to_dict()
)

In [206]:
merchant_categories = (
    transactions_df["merchant_id"]
    .map(merchant_category_map)
)

In [207]:
amount_ranges = {
    "Grocery":(50,1500),
    "Food":(80,800),
    "Fuel":(200,3000),
    "Utilities":(100,5000),
    "Healthcare":(300,10000),
    "Education":(500,30000),
    "Entertainment":(100,5000),
    "Travel":(500,20000),
    "E-Commerce":(200,25000),
    "Other":(50,10000)
}

def generate_amount(category):

    low,high = amount_ranges[category]

    return random.randint(low,high)

In [208]:
transactions_df["amount"] = [
    generate_amount(cat)
    for cat in merchant_categories
]

In [209]:
transactions_df["amount"].describe()

count    200000.000000
mean       3543.825200
std        5550.592599
min          50.000000
25%         508.750000
50%        1100.000000
75%        3587.000000
max       29979.000000
Name: amount, dtype: float64

In [210]:
transactions_df.nlargest(10,"amount")[
    ["merchant_id","amount"]
]

       merchant_id  amount
171879       M0166   29979
177891       M0253   29972
119248       M0230   29956
195151       M0162   29944
169805       M0166   29941
137768       M0296   29936
197113       M0496   29898
152208       M0466   29897
130676       M0311   29896
180608       M0311   29880

In [211]:
transactions_df["payment_status"] = np.random.choice(

    ["Success","Failed","Pending"],

    NUM_TRANSACTIONS,

    p=[0.95,0.04,0.01]

)

In [212]:
transactions_df["payment_status"].value_counts()

payment_status
Success    190072
Failed       7937
Pending      1991
Name: count, dtype: int64

In [213]:
high_value_idx = np.random.choice(
    transactions_df.index,
    1000,
    replace=False
)

In [214]:
transactions_df.loc[
    high_value_idx,
    "amount"
] = np.random.randint(
    50000,
    150001,
    1000
)

In [215]:
(transactions_df["amount"]>=50000).sum()

np.int64(1000)

In [216]:
late_night_idx = np.random.choice(
    transactions_df.index,
    500,
    replace=False
)

In [217]:
transactions_df.loc[
    late_night_idx,
    "timestamp"
] = (

    transactions_df.loc[
        late_night_idx,
        "timestamp"
    ].dt.normalize()

    + pd.to_timedelta(
        np.random.randint(2,5,500),
        unit="h"
    )

    + pd.to_timedelta(
        np.random.randint(0,60,500),
        unit="m"
    )

    + pd.to_timedelta(
        np.random.randint(0,60,500),
        unit="s"
    )

)

In [218]:
transactions_df[
    transactions_df["timestamp"].dt.hour.between(2,4)
].shape

(1857, 8)

In [219]:
failed_idx = np.random.choice(
    transactions_df.index,
    500,
    replace=False
)

transactions_df.loc[
    failed_idx,
    "payment_status"
] = "Failed"

In [220]:
transactions_df["suspicion_flag"] = False

transactions_df["suspicion_reason"] = ""

In [221]:
transactions_df.loc[
    transactions_df["amount"]>=50000,
    "suspicion_flag"
] = True

transactions_df.loc[
    transactions_df["amount"]>=50000,
    "suspicion_reason"
] = "High Value"

In [222]:
late_mask = transactions_df[
    "timestamp"
].dt.hour.between(2,4)

transactions_df.loc[
    late_mask,
    "suspicion_flag"
] = True

transactions_df.loc[
    late_mask,
    "suspicion_reason"
] = "Late Night"

In [223]:
failed_mask = (
    transactions_df[
        "payment_status"
    ]=="Failed"
)

transactions_df.loc[
    failed_mask,
    "suspicion_flag"
] = True

transactions_df.loc[
    failed_mask,
    "suspicion_reason"
] = "Failed Transaction"

In [224]:
transactions_df.to_csv(
    "../DATA/RAW/transactions_phase4_complete_raw.csv",
    index=False
)

In [225]:
# import os
# os.path.exists(
#     "../DATA/RAW/transactions_phase4_complete_raw.csv"
# )

pd.read_csv(
    "../DATA/RAW/transactions_phase4_complete_raw.csv"
).shape

(200000, 10)

In [226]:
# transactions_df.shape
# transactions_df.isnull().sum()
# transactions_df["payment_status"].value_counts()
# transactions_df["transaction_type"].value_counts()
# transactions_df["suspicion_flag"].value_counts()
# transactions_df["suspicion_reason"].value_counts()
# transactions_df["amount"].describe() 
# transactions_df.nlargest(
#     10,
#     "amount"
# )[[
#     "transaction_id",
#     "amount",
#     "payment_status"
# ]]

In [227]:
dirty_df = transactions_df.copy()

In [230]:
dirty_df.shape

# dirty_df.isnull().sum()

# dirty_df.duplicated().sum()

(200000, 10)

In [231]:
merchant_missing_idx = np.random.choice(
    dirty_df.index,
    500,
    replace=False
)

dirty_df.loc[
    merchant_missing_idx,
    "merchant_id"
] = np.nan

In [232]:
dirty_df["merchant_id"].isnull().sum()

np.int64(500)

In [234]:
device_missing_idx = np.random.choice(
    dirty_df.index,
    300,
    replace=False
)

dirty_df.loc[
    device_missing_idx,
    "device_id"
] = np.nan

In [235]:
dirty_df["device_id"].isnull().sum()

np.int64(300)

In [236]:
status_missing_idx = np.random.choice(
    dirty_df.index,
    200,
    replace=False
)

dirty_df.loc[
    status_missing_idx,
    "payment_status"
] = np.nan

In [237]:
dirty_df["payment_status"].isnull().sum()

np.int64(200)

In [238]:
duplicate_rows = dirty_df.sample(
    300,
    random_state=42
)

dirty_df = pd.concat(
    [dirty_df, duplicate_rows],
    ignore_index=True
)

In [239]:
dirty_df.shape

(200300, 10)

In [240]:
dirty_df.duplicated().sum()

np.int64(300)

In [241]:
invalid_status_idx = np.random.choice(
    dirty_df.index,
    200,
    replace=False
)

invalid_values = np.random.choice(
    ["Succes","Faild","Pendng"],
    200
)

dirty_df.loc[
    invalid_status_idx,
    "payment_status"
] = invalid_values

In [242]:
dirty_df["payment_status"].value_counts(dropna=False)

payment_status
Success    189501
Failed       8414
Pending      1986
NaN           199
Faild          73
Succes         65
Pendng         62
Name: count, dtype: int64

In [243]:
negative_idx = np.random.choice(
    dirty_df.index,
    100,
    replace=False
)

dirty_df.loc[
    negative_idx,
    "amount"
] *= -1

In [244]:
(dirty_df["amount"]<0).sum()

np.int64(100)

In [245]:
dirty_df.to_csv(
    "../DATA/RAW/transactions_dirty_raw.csv",
    index=False
)

In [247]:
os.path.exists(
    "../DATA/RAW/transactions_dirty_raw.csv"
)

pd.read_csv(
    "../DATA/RAW/transactions_dirty_raw.csv"
).shape

(200300, 10)